[package]
name = "ffi-callback"
version = "0.1.0"
edition = "2018"

[lib]
doctests = false

[dependencies]
futures = { version = "0.3", default-features = false }
tokio = { version = "0.2", features = ["full"] }

[build-dependencies]
cc = "1.0.59"
